@extends('layouts.site')
@section('title','Casale Saúde Integrada | Odontologia, Fisioterapia e Acupuntura')
@section('content')
<section class="home-hero section overflow-hidden"><div class="container-site grid items-center gap-12 lg:grid-cols-2"><div class="reveal-item"><span class="eyebrow">Cuidado humano e integrado</span><h1>Saúde cuidada por inteiro, com atenção a você.</h1><p class="mt-6 max-w-xl text-lg text-muted">Odontologia, fisioterapia e acupuntura em Piracicaba, reunidas em um espaço acolhedor.</p><div class="mt-8 flex flex-wrap gap-3"><a class="btn-primary" href="{{ route('contact') }}">Agendar atendimento</a><a class="btn-secondary" href="{{ route('treatments') }}">Conhecer tratamentos</a></div></div><img src="{{ asset('images/clinica-casale.jpg') }}" width="1200" height="800" alt="Ambiente acolhedor da Casale Saúde Integrada" class="aspect-[4/3] w-full rounded-2xl object-cover shadow-soft"></div></section>
<section class="section bg-white"><div class="container-site"><span class="eyebrow">Tratamentos</span><h2>Cuidado adequado para cada necessidade</h2><div class="mt-10 grid gap-6 md:grid-cols-3">@foreach($treatments as $t)<article class="card"><p class="eyebrow">{{ $t->category }}</p><h3>{{ $t->name }}</h3><p class="mt-4 text-muted">{{ $t->excerpt }}</p><a class="mt-6 inline-block font-bold text-green-700" href="{{ route('treatments.show',$t) }}">Conhecer tratamento →</a></article>@endforeach</div></div></section>
<section class="differentials section bg-green-900 text-white"><div class="container-site grid gap-12 lg:grid-cols-2"><div><span class="eyebrow text-beige-300">Nossos diferenciais</span><h2>Atenção individual em cada encontro</h2></div><div class="grid gap-6 sm:grid-cols-2">@foreach(['Atendimento personalizado','Profissionais qualificados','Tratamentos integrados','Clínica, domicílio e online'] as $item)<p class="differential-item">{{ $item }}</p>@endforeach</div></div></section>
<section class="section"><div class="container-site"><span class="eyebrow">Equipe</span><h2>Profissionais que cuidam com presença</h2><div class="mt-10 grid gap-6 md:grid-cols-3">@foreach($professionals as $p)<article class="card overflow-hidden p-0"><img src="{{ $p->image_path && str_starts_with($p->image_path,'images/') ? asset($p->image_path) : Storage::url($p->image_path) }}" width="600" height="760" loading="lazy" alt="{{ $p->name }}" class="aspect-[4/5] w-full object-cover"><div class="p-6"><h3>{{ $p->name }}</h3><p class="mt-2 text-muted">{{ $p->title }}</p><a class="mt-5 inline-block font-bold text-green-700" href="{{ route('professionals.show',$p) }}">Ver perfil →</a></div></article>@endforeach</div></div></section>
<section class="section bg-beige-100"><div class="container-site text-center"><span class="eyebrow">Vamos conversar?</span><h2>Encontre o cuidado adequado para você</h2><p class="mx-auto mt-5 max-w-2xl text-muted">Converse com nossa equipe para esclarecer dúvidas e entender qual atendimento faz mais sentido.</p><a class="btn-primary mt-8" href="https://wa.me/551934242812" target="_blank" rel="noopener">Conversar pelo WhatsApp</a></div></section>
@endsection
